[package]
edition = "2021"
name = "migration"
publish = false
rust-version = "1.85.0"
version = "0.1.0"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }

[dependencies.sea-orm-migration]
features = [
  "runtime-tokio-rustls",  # `ASYNC_RUNTIME` feature
  "sqlx-postgres",  # `DATABASE_DRIVER` feature
]
version = "2.0.0-rc"
