apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slacker.fullname" . }}
  labels:
    {{- include "slacker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "slacker.databaseUrl" . | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.config.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.config.googleClientSecret | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ .Values.config.encryptionKey | quote }}
