apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slacker.fullname" . }}-workspaces
  labels:
    {{- include "slacker.labels" . | nindent 4 }}
type: Opaque
stringData:
  workspaces.yaml: |
    {{- range $name, $config := .Values.workspaces }}
    {{ $name }}:
      app_token: {{ $config.appToken | quote }}
      bot_token: {{ $config.botToken | quote }}
    {{- end }}
